# The CUDA version matters to some degree, and must at least work with the
# driver used on the container host.
ARG BASE_CUDA_DEV_CONTAINER=nvidia/cuda:12.8.1-devel-ubuntu24.04
ARG BASE_CUDA_RUN_CONTAINER=nvidia/cuda:12.8.1-runtime-ubuntu24.04

# `release` or `debug`
ARG RUST_TARGET_TYPE="release"

# NOTE(canardleteer): It's easier to install Rust on a CUDA image, than it is
#                     to install CUDA on a Rust image.
FROM $BASE_CUDA_DEV_CONTAINER AS build
ARG RUST_TARGET_TYPE

# Install required Ubuntu packages
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && \
    apt install -y --no-install-recommends nvidia-opencl-dev curl && \
    rm -rf /var/lib/apt/lists/*

RUN useradd -ms /bin/bash graxil
USER graxil
WORKDIR /home/graxil

# Grab the "latest" Rust.
#
# NOTE(canardleteer): I'm a little confused by the `rust-toolchain` file in this
#                     repo, AFAIK, it's similar to the `cargo` supported
#                     `rust-toolchain.toml` file, but I'm not attempting to
#                     capture changes to the CI build system in this PR.
ADD --chmod=755 https://sh.rustup.rs /home/graxil/rustup.sh
RUN ./rustup.sh -y
ENV PATH="/home/graxil/.cargo/bin:${PATH}"

# Cache dependency changes first.
COPY Cargo.toml Cargo.lock ./
RUN cargo fetch

# Then cache whatever else is required via an include.
COPY src ./src
COPY kernels ./kernels
COPY ./log4rs_sample.yml ./

# The default `hybrid` feature should pick up the `nvidia-opencl-dev` just fine.
RUN cargo build --$RUST_TARGET_TYPE

FROM $BASE_CUDA_RUN_CONTAINER AS runtime

ARG RUST_TARGET_TYPE

RUN apt update && \
    apt install -y --no-install-recommends pocl-opencl-icd clinfo && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /etc/OpenCL/vendors && \
    echo "libnvidia-opencl.so.1" > /etc/OpenCL/vendors/nvidia.icd

RUN useradd -ms /bin/bash graxil
USER graxil
WORKDIR /home/graxil

COPY --from=build /home/graxil/target/$RUST_TARGET_TYPE/graxil /home/graxil/target/$RUST_TARGET_TYPE/gpu_test ./
ENTRYPOINT [ "./graxil" ]
